entrypoint: test out HTTP version 1.1 and bigger buffer for transport issues
In some situation when cloning from gitee we run into problems with the
https transport. If this is due to gitee servers or middleboxes is
unclear. Try to use HTTP 1.1 and an increased buffer for now.

Cmd('git') failed due to: exit code(128)
  cmdline: git clone https://gitee.com/openharmony/third_party_noto-cjk.git /github/workspace/hub-mirror-cache/third_party_noto-cjk
  stderr: 'Cloning into '/github/workspace/hub-mirror-cache/third_party_noto-cjk'...
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
error: 2738 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output'

Signed-off-by: Stefan Schmidt <stefan@datenfreihafen.org>